#--------------------------GROPROCESSAMENTO APLICADO - PPEC - UFBA - 2020.2 - JULIO PEDRASSOLI------------------------#

#--------------------------MODULO 2-----------------------------------------------------------------------------------#

# DICA: ANTES DE COMECAR CRIE UM NOVO PROJETO A AJUSTE A PASTA DE DESTINO E ORIGEM DOS DADOS DESTE PROJETO -> SESSION -> SET WORKING DIRECTORY.

# OBJETIVOS: CARREGAMENTO DE ARQUIVOS LOCAIS, MERGE E JOIN EM TABELAS (DATA FRAMES) E GEOCODIFICAO POR MEIO DE USO 
# DE API (APPILCATION PROGRAMING INTERFACE).

# INSTALACAO E CARREGAMENTO DOS PACOTES NECESSARIOS NESTE MODULO
# PACOTE hereR (PARA ACESSAR A API DE GEOCODIFICACAO DA NOKIA/HERE) E O PACOTE RSQLite (QUE VAI CARREGAR A BASE DE CEP DOS CORREIOS):

install.packages("hereR")
install.packages("RSQLite")
library(hereR)
library(RSQLite)

# CARREGUE O ARQUIVO GERADO NO MODULO 1, O QUAL CONTEM OS REGISTROS DE INTERNACOES POR DIABETES E HIPERTENSAO EM UM DETERMINADO
# RECORTE TEMPORAL PARA SALVADOR (PERIODO DE ANALISE DEFINIDO NO MODULO ANTERIOR):

comorbsssa19 <- read.csv("banco_ssa_comorb_2019.csv")

# RELEMBRE A ESTRUTURA DO ARQUIVO DANDO CLIQUE DUPLO SOBRE ELE NA ABA "ENVIRONMENT". RELEMBRE TAMBEM QUE ELE POSSUI O CAMPO CEP 
# E QUE A INTENCAO, NESTE MODULO, É UTILIZAR ESTE CAMPO PARA ATRIBUIR UM ENDERECO ESTIMADO PARA CADA AIH (AUTORIZACAO DE INTERNACAO HOSPITALAR).

# PARA ISSO, O IDEAL E QUE ANTES DE REALIZARMOS UMA BUSCA POR COORDENADAS GEOGRAFICAS PARA CADA AIH, CONSEGUISSEMOS UM ENDERECO COM MAIOR
# COMPLETUDE ALEM DO CEP. USAREMOS A BASE DE DADOS DOS CORREIOS, QUE NOS DA EXATAMENTE O QUE QUEREMOS: PARA CADA CEP UMA RUA, 
# BAIRRO E CIDADE.ESSA BASE, CAHAMADA "DIRETORIO NACIONAL DE ENDERECOS", PODE SER ACESSADA MAS TEM UM CUSTO (http://shopping.correios.com.br/wbm/store/script/wbm2400902p01.aspx?cd_company=ErZW8Dm9i54=&cd_department=SsNp3FlaUpM=)
# PARA FINS DESTE EXERCICIO, DISPONIBILIZO UMA COPIA MAIS ANTIGA DESTA BASE, SALVA LOCALMENTE.
# TAL BASE MESTA EM UM FORMATO CHAMADO DE ARQUIVO "DBASE" E PARA ACESSA-LA PRECISAMOS DO PACOTE RSQLITE INSTALADO ANTERIORMENTE.

# CRIE UM OBJETO NO R QUE ARMAZENA A CONEXAO COM O ARQUIVO DOS CORREIOS (cep.db3), LEMBRE QUE O ARQUIVO DEVE ESTAR NA PASTA DE DIRETORIO
# DEFINIDA NO INICIO DO EXERCICIO:

con <- dbConnect(RSQLite::SQLite(), "cep.db3")

# AGORA CRIE OUTRO OBJETO QUE CARREGUE OS DADOS DA TABELA CONECTADA:

cep <- dbReadTable(con, "cep")

# E POR FIM RENOMEIE A COLUNA 2, CHAMANDO-A DE "CEP", ASSIM FACILITARA A UNIAO COM A BASE DO DATASUS QUE CRIAMOS NO MODULO ANTERIOR:

colnames(cep)[2] <- "CEP"

# O PASSO SEGUINTE SERA JUNTAR (MERGE) OS DADOS DO CEP DOS CORREIOS (LOGRADOURO, CIDADE E ESTADO) COM A BASE DATASUS, USANDO O QUE CHAMAMOS
# DE CHAVE UNICA DE LIGACAO (OU CHAVE PRIMARIA, SE PREFERIREM), E NO CASO DA BASE DOS CORREIOS (QUE A TABELA QUE SERA UNIDA) CHAMAMOS DE 
# CHAVE ESTRANGEIRA. LEMBRE-SE QUE AGORA AMBOS OS CAMPOS QUE USAREMOS COMO CHAVE DE LIGACAO TEM O MESMO NOME.

# NO PROCESSO A SEGUIR CRIAMOS UM NOVO OBJETO CONTENDO A JUNCAO DAS BASES:

comorb_cep_join <- merge(comorbsssa19, cep, by="CEP", all.x = TRUE)

# VAMOS CRIAR UM NOVO CAMPO NO DATAFRAME CONCATENANDO OS DADOS DE ENDERECO EM UM UNICO NOVO CAMPO, POIS ESTA SERA A STRING QUE 
# PASSAREMOS NO PROCESSO DE GEOCODIFICACAO. PERCEBA, NOVAMENTE, QUE A MANIPULACAO DE UM CAMPO NO DATA FRAME, COMO NA CRIACAO, UTILIZAMOS A 
# SINTAXE $ (CIFRAO). PARA ISTO
# UTILIZAMOS A FUNCAO BASE DO R "PASTE":

comorb_cep_join$ENDERECO <- paste(comorb_cep_join$TXT_LOCALIDADE, 
                                  comorb_cep_join$TXT_BAIRRO, 
                                  comorb_cep_join$TXT_CIDADE_UF,
                                  comorb_cep_join$CEP)

# NAVEGUE PELA NOVA TABELA E VERIFIQUE QUE NOVOS CAMPOS FORAM ADICIONADOS AO FINAL, VINDOS DA BASE DOS CORREIOS, ALEM DO CAMPO CONCATENADO.
# COMO A TABELA TEM MUITAS COLUNAS, PARA ACESSAR OS ULTIMOS CAMPOS CLIQUE EM ">>" PARA AVANCAR.
# AGORA TEMOS A POSSIBILIDADE DE USAR O CEP E O NOME DO LOGRADOURO NA BUSCA DE UM PAR DE COORDENADAS PARA CADA AIH.



#--------------------------GEOCODIFICACAO DE ENDERECOS------------------------#

# RESUMIDAMENTE, GEOCODIFICAR E O PROCESSO DE ATRIBUIR UM PAR DE COORDENADAS A UM ENDERECO (https://en.wikipedia.org/wiki/Geocoding)
# A MANEIRA CLASSICA DE GEOCODIFICACAO, QUE PODE SER PROCESSADA LOCALMENTE, ENVOLVE O USO DE UM ARQUIVO DE LOGRADOUROS ESTRUTURADO, 
# COM INFORMACOES ESPECIFICAS QUE DIVIDEM OS NOMES DOS LOGRADOUROS EM COMPONENTES, TEM ANOTADOS OS INTERVALOS DE CEP A DIREITA E ESQUERDA 
# DAS VIAS, TEM GEOMETRIA VETORIAL LIMITADA A CADA FACE DE QUADRA (NOVO OBJETO GEOGRAFICO A CADA LINHA), ENTRE OUTROS, E PRECISA
# DO USO DE UM SIG CAPAZ DE PROCESSAR O ALGORITMO. UMA ABORDAGEM MAIS MODERNA SE DA COM A UTILIZACAO DE SERVICOS VIA API, QUE CONSISTE EM
# PASSAR UMA STRING DE ENDERECOS DE FORMA "REPETITIVA" PARA UM PROVEDOR DE MAPAS, O QUAL RETORNARA, POR UMA OPERACAO SEMANTICA, 
# O PAR DE COORDENADAS DO ENDERECO SOLICIITADO. oS RESULTADOS TEM ACURACIA VARIAVEL, DEPENDE DA ESCALA, DA QUALIDADE DA BASE, ETC. MAS
# DISCUTIREMOS ESTES DETALHES NA AULAS SINCRONAS.

# EXISTEM DIVERSAS APIS DE GEOCODIFICACAO DISPONIVEIS TAIS COMO O GOOGLE GOEOCODE API, NOMINATIM, HERE MAPS, ENTRE OUTRAS.
# NESTE EXERCICIO UTILIZAREMOS A API DO HERE MAPS, POIS COM ELA TEREMOS ACESSO A 250.000 CONSULTAS DE ENDERECOS DE FORMA GRATUITA
# NA CONTA FREEMIUM, POR MES. PORTANDO, ANTES DE COMECAR O PROCESSO SEGUINTE VOCE PRECISARA DE UMA "CHAVE DE API". 
# PARA SOLICITAR UMA CHAVE CRIE UMA CONTA FREEMIUM NO HERE (https://developer.here.com/) - SE AINDA ESTA COM
# DUVIDAS? ASSISTA A ESTE PEQUENO VIDEO: https://www.youtube.com/watch?v=EdX8cxHVqHY.

# EM SEU PROJETO, NO CONSOLE DE DESENVOLVEDOR NO SITE DO HERE, GERE UMA CHAVE DE API, COPIE E COLE NA LINHA DE CODIGO "set_key". 
# AQUI ESTAMOS DEFININDO QUAL PROJETO VAI SER CONSUMIDO DURANTE O PROCESSO DE GEOCODIFICACAO NO R. 
# LEMBRE-SE QUE NO INICIO DESTE MODULO VOCE JA INSTALOU E CARREGOU A LIVRARIA hereR, E SE POR ACASO VOCE PAROU E FECHOU O RSTUDIO
# ANTES DE CHEGAR AQUI, PRECISARA RECARREGA-LA. ISTO VALE PARA QUALQUER LIVRARIA QUE PRETENDA USAR.
# SETANADO A CHAVE DE API":


set_key("COLOQUE SUA CHAVE DE API AQUI")

# COM A CHAVE DEFINIDA VAMOS UTILIZAR A FUNCAO 'geocode' DO PACOTE hereR. A SINTAXE E SIMPLES: DEFINA UM OBJETO NO R PARA RECEBER 
# OS RESULTADOS, ESSES RESULTADOS VIRAO DA FUNCAO GEOCODE SENDO APLICADA SOBRE A COLUNA "ENDERECO" DE NOSSA BASE DE DADOS.
# OBSERVE, NOVAMENTE, QUE PARA SELECIONAR UMA COLUNA EM UM DATAFRAME USAMOS $ (CIFRAO):

comorbs_geo <- geocode(c(addresses = comorb_cep_join$ENDERECO))

# PARA UMA COMPREENSAO DETALHADA DO PACOTE DE GEOCODIFICACAO, RECOMENDO FORTEMENTE A CONSULTA A DOCUMENTACAO: https://munterfinger.github.io/hereR/
# TENHA PACIENCIA, O PROCESSO PODE SER DEMORADO POIS HA UM LIMITE DE SOLICITACOES POR SEGUNDO, REGULADO PELA API POR QUESTOES DE TRAFEGO
# DE DADOS.
# QUANTO MAIOR A QUANTIDADE DE DADOS VOCE FILTROU DO DATASUS MAIOR O TEMPO DE PROCESSAMENTO. LEMBRE-SE TAMBEM DO LIMITE MENSAL DE 
# 250.000 CONSULTAS POR API.
# CONSULTE A NOVA TABELA GERADA, VERIFIQUE QUE UM NOVO CAMPO COM O PAR DE COOREDANADAS FOI ADICIONADO.

# O MODLULO 3 FARA USO DESTA TABELA, DESTA VEZ INTRODUZINDO UM NOVO SOFTWARE: O QGIS

# ANTES DE EXPORTAR OS RESULTADOS E PARTIR PARA O QGIS, VAMOS JUNTAR A TABELA GEOCODIFICADA COM A TABELA ORIGINAL DO DATASUS,
# ASSIM PODEREMOS TER O BANCO COMPLETO PARA ANALISES FUTURAS

colnames(comorbs_geo)[1] <- "X"

comorb_geo_merged <- merge(comorb_cep_join, comorbs_geo, by="X", all.x = TRUE)

# O CAMPO "X" SERA A CHAVE UNICA DE LIGACAO NESTE CASO.

# EXPORTE A BASE DE DADOS GEOCODIFICADA

write.csv(comorb_geo_merged, 'comorbs_geocode_merged.csv')

#--------------------------FIM DO MODULO 2-----------------------------------------------------------------------------------#

